### ISSUE TITLE
Error: Cannot find module ...

### ISSUE THREAD

**Issue by MonkeyPlayzMC** [TheRacingLion/Discord-SelfBot#1]
So i keep getting a error ;-;

and I keep trying to reinstall but it just wont work !!

here see for urself

https://gyazo.com/b0ef55802d43d8e850d3e213126c06a6

**Comment by jayden000** [comment]
Same error here

**Comment by MonkeyPlayzMC** [comment]
@DevJayden000 or @TheRacingLion  Do you know how to fix?

**Comment by TheRacingLion** [comment]
Sorry, only saw this now. Will push a fix later today.

**Comment by TheRacingLion** [comment]
@MonkeyPlayzMC Are you on the lastest version of the selfbot? Seems to start up fine for me.
Make sure you installed your modules correctly, if the installer file does not work, simply open a console inside the folder where your selfbot files are and type `npm i`, that should install every module the bot needs to work, I have double checked and `asyncawait` is already a dependency of the bot, so either the installer file or `npm i` should do it. Let me know if you still have the same problem.
https://gyazo.com/43e59fb0ceed677411b0525ebb9e1bc4

**Comment by MonkeyPlayzMC** [comment]
Like from git bash or gui or???

**Comment by MonkeyPlayzMC** [comment]
im getting errors when I do this. im currently on windows 10

**Comment by MonkeyPlayzMC** [comment]
https://gyazo.com/b47a9ff88b49495196867468e46a4154

**Comment by MonkeyPlayzMC** [comment]
I got it to install async-await but still errors

**Comment by MonkeyPlayzMC** [comment]
what it gives me is

C:\Users\choco\Desktop\Discord-SelfBot-master>title Discord Selfbot

C:\Users\choco\Desktop\Discord-SelfBot-master>node self.js
module.js:591
    throw err;
    ^

 in JSON at position 129oco\Desktop\Discord-SelfBot-master\config\config.json: Unexpected token
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\choco\Desktop\Discord-SelfBot-master\self.js:9:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

C:\Users\choco\Desktop\Discord-SelfBot-master>goto START

C:\Users\choco\Desktop\Discord-SelfBot-master>node self.js

**Comment by MonkeyPlayzMC** [comment]
@TheRacingLion Can I see your config.json Just remove the token for meh

**Comment by MonkeyPlayzMC** [comment]
https://gyazo.com/a1ca362a9ea098301c7c41cbc387d301

**Comment by TheRacingLion** [comment]
My config.json is the same as the default one, make sure you did not place a comma on the last line of the json, cause it will make it error.

**Comment by MonkeyPlayzMC** [comment]
@TheRacingLion No it's not like that I removed the token to show ya
{
  "token": "",
  "ownerID": "251234116790517761",
  "prefix": "$",
  "rotatePlayingGame": true,
  "rotatePlayingGameTime" : 150000,
  "defaultStatus": "idle",
  "mentionNotificator": {
    "inConsole": false
    "inNotificationChannel": false
  },
  "eventNotificator": {
    "inConsole": false
    "inNotificationChannel": false
  },
  "notificationChannelID": "",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": true
}

**Comment by MonkeyPlayzMC** [comment]
but I have the token in the config.json

**Comment by TheRacingLion** [comment]
Removed tag command until I figure out a better way of putting it into the bot, it should work fine now if you get latest changes and install modules again.
