### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by MrMysterius** [TheRacingLion/Discord-SelfBot#10]
If i start the run.bat i get the same error over and over http://prntscr.com/eogfvp

**Comment by TheRacingLion** [comment]
Can you give more info about this error? Like, what version of node are you running (check by doing `node -v` in console), what is your OS, etc. Ty.

**Comment by NoGameNoLife8** [comment]
I got this error instead when I tried to start the run.bat file, over and over.

https://cdn.discordapp.com/attachments/283492249831079936/296253308602023936/unknown.png

**Comment by MrMysterius** [comment]
Node v0.12.2
OS: Windows 7
And thats the whole Error on the Screenshot more i cant tell really :/

**Comment by TheRacingLion** [comment]
Try installing the most recent node version, because that is most likely the problem.
Go here and choose the option that you are using: https://nodejs.org/en/download/current/

**Comment by MrMysterius** [comment]
:/ I cant istall a newer version of node.js for some reason i am trying to fix it

**Comment by MrMysterius** [comment]
Okay it works now thanks for the support ^^
