### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 2CAN0** [TheRacingLion/Discord-SelfBot#11]
IK this isn't the right section but I didn't know where to place else.
Is it possible to let the selfbot type >payday every 5 minutes or give updates every 5 minutes.

**Comment by TheRacingLion** [comment]
I would suggest learning some basic javascript if you want to add your own commands and utilities to the selfbot. Having said that, I would most likely use the `setInterval` function.
```js
function saySomething () {
  // Do something to make the bot say something
}
setInterval(saySomething, timeInMilliseconds)
```
