### ISSUE TITLE
Error message while trying to start run.bat

### ISSUE THREAD

**Issue by NoGameNoLife8** [TheRacingLion/Discord-SelfBot#12]
Title says it all, but the error keeps on repeating itself till I closed the .bat file.

https://cdn.discordapp.com/attachments/283492249831079936/296253308602023936/unknown.png

**Comment by TheRacingLion** [comment]
There is most likely something wrong with your config file. As it says on the error. I would check for commas missing or other stuff you might be doing wrong inside the file.
