### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by RickRolled7891** [TheRacingLion/Discord-SelfBot#13]
> > Discord_Selfbot@2.1.0 start /home/rick/Discord-SelfBot
> node self.js

sh: 1: node: not found

npm ERR! Discord_Selfbot@2.1.0 start: `node self.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the Discord_Selfbot@2.1.0 start script.
npm ERR! This is most likely a problem with the Discord_Selfbot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node self.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Discord_Selfbot
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/rick/Discord-SelfBot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rick/Discord-SelfBot/npm-debug.log
npm ERR! not ok code 0

**Comment by RickRolled7891** [comment]
I am on a linux

**Comment by MrMysterius** [comment]
i think you need at least node v 4.0.0 that was the problem at least for me but dont ask me i am a silly guy ^^

**Comment by RickRolled7891** [comment]
I can't get node to work on my vps. I have been trying but idk

**Comment by RickRolled7891** [comment]
Do you have discord? so I can talk to someone about it

**Comment by RickRolled7891** [comment]
if so add RickRolled7889#1159

**Comment by RickRolled7891** [comment]
Alright I got it fixed Thanks for helping?
