### ISSUE TITLE
Commands other than "me" aren't working

### ISSUE THREAD

**Issue by DeerAndy** [TheRacingLion/Discord-SelfBot#14]
So I had some issues with adding my own paste command (lenny face) and the console made a booboo so I did everything from scratch and all was good with defaults until I tried to use the paste and ping commands that only displayed the trigger for the command and didn't replace the text.

**Comment by TheRacingLion** [comment]
Sorry! Only saw this now! Let me know if the issue still stands. I will look into it asap.

**Comment by DeerAndy** [comment]
It works now, ha, thanks. :)

**Comment by TheRacingLion** [comment]
I will still push a fix for a problem I think might have caused it to act that way. Thanks for reporting!
