### ISSUE TITLE
Eval commands

### ISSUE THREAD

**Issue by RickRolled7891** [TheRacingLion/Discord-SelfBot#17]
Alright I see in the commands for eval is me(eval self
me( is my prefix
I do me(eval self and it gives a error in the console that it is longer then 2000 words and I wanted to see what it does. Also I was wondering what other eval commands I can do

**Comment by TheRacingLion** [comment]
@RickRolled7891 Eval command evaluates the thing you give it as if it was plain JavaScript code. `self` is the main selfbot client variable so the thing you got on the console was just the bot saying he couldnt fit all the stuff inside of the `self` variable, which is A LOT of stuff, inside 1 discord message (Which has a character limit of 2000). Eval command is mostly used for quick things were you can check how many friends you have, in how many servers you are, etc. Some example eval commands are:

- `'This is some text'` (Will eval this string, which basicly returns it again)
- `self.guilds.size` (How many servers you are in)
- `self.relationships.size` (How many friends you have)
- `let x = 5; let y = 10; console.log(x + y)` (Evaluates this expression)

Of course these expressions can get A LOT MORE COMPLICATED, and the eval function also exposes your entire computer when running any expression, which is one of the reasons it makes sure only the owner of the selfbot can evaluate anything.
Hope it helped, ~Lion.
