### ISSUE TITLE
Its not working for me module.js:591 throw err^

### ISSUE THREAD

**Issue by VSabertail** [TheRacingLion/Discord-SelfBot#19]
syntax error token M is at position 15
then keeps saying goto start
node self.js

**Comment by VSabertail** [comment]
C:\WINDOWS\system32>goto START

C:\WINDOWS\system32>node self.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\self.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

C:\WINDOWS\system32>goto START

C:\WINDOWS\system32>node self.js

**Comment by VSabertail** [comment]
i have been trying to fix this for days then i decided to get help and i don't know how to fix this and i'm an expert with computers

**Comment by VSabertail** [comment]
i have tried to install a later version of node and it still wont work

**Comment by VSabertail** [comment]
it might be an issue with self.js
cause i cant find what to open it with
and same with the json files
ive tried opening self.js with notepad (ik it doesnt work but i tried) and i tried with java

**Comment by TheRacingLion** [comment]
Huh? After you install node and run the `installer.bat` file (if the file doesnt work just open a terminal inside of the folder where your files are and run `npm i`). After that you just run the `run.bat` file that was created after you run the installer (or run `node self.js` in a terminal). You can right click the `.js` file and click on open with Notepad++, but that will just show the code. To actually run it you need the console to do so. By the looks of the second comment (`C:\WINDOWS\system32`) it looks like the computer is trying to run it with administrator permissions and not in the file where the `self.js` is, thats why it errors, because it isnt able to find it.

**Comment by VSabertail** [comment]
oh
thats too much tho i need to fix it is there an easy fix?

**Comment by TheRacingLion** [comment]
There isnt really anything to fix. You are just probably starting it in the wrong folder. Try opening a terminal inside of the folder where the selfbot files are and running `node self.js`. Not to mention `syntax error token M is at position 15` seems to be a config file error, but the second one with `C:\WINDOWS\system32` is already related to the starting of the bot itself.

**Comment by VSabertail** [comment]
well i have an error running self well i runned it with node.js and i cant get it back to its default and i cant change it when i try to run it it says syntax error this is all with the .js files which i set the file location as node and i cant change that

**Comment by VSabertail** [comment]
need help changing that

**Comment by VSabertail** [comment]
well i saw it was changed but it still has node icon but then it has opened with microsoft thing thats why there is a syntax error but i need help with that too

**Comment by AriRexouium** [comment]
Are you trying to run the batch file inside of 7zip or WinRAR?

**Comment by VSabertail** [comment]
idk
which should i use

**Comment by AriRexouium** [comment]
Don't use any, extract the files first before you try to start up the bot.

**Comment by VSabertail** [comment]
i did the files are messed up

**Comment by AriRexouium** [comment]
From what I can tell, you're trying to run the bot with Administrative permissions, thus it's looking for `self.js` in `C:\WINDOWS\system32\`.
- If you're right clicking on the batch file and clicking `Run as Administrator`, don't do that. Just run the file as any other file.
- If the file is running as Administrator regardless, right click on the batch file and navigate to `Properties > Comparability` and uncheck `Run This Program As An Administrator`. be sure to click `OK` (this will apply the settings and close the window). Now try to run the file.

**Comment by TheRacingLion** [comment]
The comment above should fix it. Make sure you are doing everything right. Feel free to re-open this if the problem still happens.
