### ISSUE TITLE
When "npm start" is run

### ISSUE THREAD

**Issue by bsnyde** [TheRacingLion/Discord-SelfBot#20]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart Discord_Selfbot@2.1.2
6 info start Discord_Selfbot@2.1.2
7 verbose unsafe-perm in lifecycle true
8 info Discord_Selfbot@2.1.2 Failed to exec start script
9 verbose stack Error: Discord_Selfbot@2.1.2 start: `node self.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Discord_Selfbot@2.1.2
11 verbose cwd /Users/***********/Downloads/Discord-SelfBot-master
12 error Darwin 16.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.3.0
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error Discord_Selfbot@2.1.2 start: `node self.js`
17 error Exit status 1
18 error Failed at the Discord_Selfbot@2.1.2 start script 'node self.js'.
18 error This is most likely a problem with the Discord_Selfbot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node self.js
18 error You can get their info via:
18 error     npm owner ls Discord_Selfbot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by TheRacingLion** [comment]
I would try to update node to a 7+ version, because you seem to be running it on version 4.3.0. If that does not work, feel free to create a new issue or re-opening this one.
