### ISSUE TITLE
Command messages auto deleting, the command line and the message that's posted

### ISSUE THREAD

**Issue by DeerAndy** [TheRacingLion/Discord-SelfBot#23]
Hello again, so I'm using the me command to post custom announcements and it'll post the me command delete the "/me text" then it'll delete the new message that just says "text" with the side border, etc etc after a few seconds. This didn't happen previously in other builds with less going on in the config file.

**Comment by AriRexouium** [comment]
Just change `deleteCommandMessagesTime` to `false`. This however will not delete the command you executed.

**Comment by washingdone** [comment]
any update on this?

**Comment by DeerAndy** [comment]
Just set it to false, it still removes the trigger/command.

**Comment by TheRacingLion** [comment]
Should be fixed in the PR mentioned above. Feel free to re-open or create a new issue if this is still a problem.
