### ISSUE TITLE
"Unexpected token M in JSON at position 15" (SyntaxError)

### ISSUE THREAD

**Issue by Feyko** [TheRacingLion/Discord-SelfBot#26]
Hey. When i want to start the bot, the console return me that :
![image](https://cloud.githubusercontent.com/assets/29102324/26642487/32d3e26e-462e-11e7-910a-551d86f672f5.png)
Can i have help to fix that ? Thanks~

**Comment by TheRacingLion** [comment]
Make sure that the token inside your `config.json` file is inside parentheses, and make sure that you are not missing any commas between lines. Most likely a problem on your end with the config file.

**Comment by Feyko** [comment]
The problem is with the parentheses i think. But i dont know where i need to place it. Can you show me, please ?

**Comment by NurdOfficial** [comment]
show an image of your config

**Comment by AriRexouium** [comment]
> show an image of your config

Protect your token!

**Comment by NurdOfficial** [comment]
yes yes that is very important

**Comment by Feyko** [comment]
Here it is
![image](https://cloud.githubusercontent.com/assets/29102324/26686678/0156d906-46ee-11e7-904b-35a8b5433526.png)

**Comment by NurdOfficial** [comment]
first of all take away the ("") around the token and keep one of the quotes other then that I don't see a problem

**Comment by Feyko** [comment]
If i do that, the console return an error about a config error : Invalid ownerID. Must be a string of your Discord ID.

**Comment by NurdOfficial** [comment]
Your ownerID isnt your name and discrim. if you right click on your self and click copy id
thats your ownerID

**Comment by Feyko** [comment]
If i do that, the console return an error about a config error : Invalid ownerID. Must be a string of your Discord ID.

**Comment by Feyko** [comment]
Ok thanks, this error is fixed. But now, the console return the same error than before : Unexpected token M in JSON at position 16

**Comment by TheRacingLion** [comment]
Mind showing a picture of the updated config file? With the token protected like you did before. There is most likely something else wrong with it.

**Comment by Feyko** [comment]
Yeah, sure : 
![image](https://cloud.githubusercontent.com/assets/29102324/26762714/0a04de80-4947-11e7-9533-005ff0fedb10.png)

**Comment by TheRacingLion** [comment]
Your `token` line should look like this:
`"token": "Mteitdjgitgj",`
and not like this:
`"token": "("Mteitdjgitgj")",`

Edit: When I said in the first comment `parentheses`, I meant to say `quotation marks`, blame my poor english. ;)

**Comment by Feyko** [comment]
YAY, THAT'S WORK ! Thanks !

**Comment by Feyko** [comment]
But now, i just wanted to create a command... and that's not working...
There is the code : 
![image](https://cloud.githubusercontent.com/assets/29102324/26764274/2f24c0aa-4964-11e7-8d6b-69388c18c84e.png)
And the error : 
![image](https://cloud.githubusercontent.com/assets/29102324/26764279/3d1c6924-4964-11e7-9565-0230ea8d31ad.png)

**Comment by TheRacingLion** [comment]
```js
// Optional comment string to describe the command.
module.exports = (self) => {
  self.registerCommand('mlem', function (msg, args) {
    this.embed(msg, { // Send an embed
      title: 'Embed title',
      description: 'Embed description',
      color: 4627433
    })
  })
}
```
This is taken from the command example in the readme. You placed some parentheses where they arent suppost to be and you are missing some closing brackets on some places. Also change `deleteDelay` to an actual number in milliseconds or just remove it from the code like in the example above. If at anytime the code of a command does not work, check it against the code examples from the readme to see what is wrong.
