### ISSUE TITLE
It says UnClean WS close: 4004: Authentication failed.

### ISSUE THREAD

**Issue by MrRay70915** [TheRacingLion/Discord-SelfBot#27]
I've been getting this error Everytime I want to boot up the bot, can somebody help me, Cause I don't know what do do...

**Comment by ghost** [comment]
Check your token. It's probably not correct

**Comment by TheRacingLion** [comment]
Re-copy your discord token into the `config.json` file and try again. Everytime you change your discord name, or change your discord password, the token changes and you need to re-copy into the config file. Its just how discord works.
