### ISSUE TITLE
Hey, I just want to know why this isn't working.

### ISSUE THREAD

**Issue by hanmindev** [TheRacingLion/Discord-SelfBot#32]
I ran the installer after putting my discord # and token, and when I run "run", this shows up

Error: Cannot find module 'eris'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Hanmin\Desktop\Discord-SelfBot-master\self.js:7:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by VSabertail** [comment]
same issue

**Comment by TheRacingLion** [comment]
Sometimes the installer faills to do its thing. When that happens you need to open the folder where your selfbot files are located and then `Shift + right mouse click` and then select `open command window here`, once a black window opens type `npm i` in it and then press enter. Once it finishes and you try to run the selfbot again it should work.

**Comment by hanmindev** [comment]
I'm still getting this:


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1487:SSL alert number 20
npm ERR! 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:656:
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hanmin\Desktop\Discord-SelfBot\npm-debug.log

**Comment by CursedSkullx** [comment]
I recently updated my windows and it does not feature the command prompt in the file viewer or in the Shift Right click menu. Is there any other way?

**Comment by delphiactual** [comment]
"windowsKey+R" then type `cmd`
