### ISSUE TITLE
Throw err;

### ISSUE THREAD

**Issue by Swordington** [TheRacingLion/Discord-SelfBot#36]
![screen shot 2017-06-19 at 7 47 24 pm](https://user-images.githubusercontent.com/25911649/27311674-3024a7b6-5528-11e7-8408-277d530c8f05.png)

**Comment by TheRacingLion** [comment]
@QuinnTDIP everytime it says `Cannot find module 'XXX'` use `npm i XXX`, in this case use `npm i superagent`
