### ISSUE TITLE
Error when running "npm i" (Mac)

### ISSUE THREAD

**Issue by willrkwan** [TheRacingLion/Discord-SelfBot#39]
![screen shot 2017-07-12 at 10 51 28 am](https://user-images.githubusercontent.com/30124026/28129328-1f0512de-66f0-11e7-8685-a25a2a81a02a.png)
Help?

**Comment by delphiactual** [comment]
Looks like you skipped some steps or were not in the directory you downloaded Discord-Selfbot too

**Comment by TheRacingLion** [comment]
@lieflief You need to run the `npm i` command inside of the directory where all your selfbot files are.
