### ISSUE TITLE
Embeds dont have authors

### ISSUE THREAD

**Issue by MaybeGoogle** [TheRacingLion/Discord-SelfBot#43]
I'm doing -me hello and it turns out as:
<img width="71" alt="screen shot 2017-07-14 at 7 46 02 pm" src="https://user-images.githubusercontent.com/30007491/28235093-1af2011e-68cd-11e7-8791-737e4b6f6d37.png">

If I do -me @bob hello it says:
<img width="109" alt="screen shot 2017-07-14 at 7 47 06 pm" src="https://user-images.githubusercontent.com/30007491/28235107-41938f22-68cd-11e7-8b19-a89fb647f316.png">
(theres nobody called bob, but when I do that with a real tag its the same, but they are tagged)

I don't even know what -me @bob @joe does

**Comment by TheRacingLion** [comment]
@eruzang You need to use `me user USER-YOU-WANT-TO-QUOTE text`
Refer to [here](https://github.com/TheRacingLion/Discord-SelfBot/wiki/Selfbot-Commands#me) for more info on this command.
