### ISSUE TITLE
What javascript code can you evaluate

### ISSUE THREAD

**Issue by MaybeGoogle** [TheRacingLion/Discord-SelfBot#47]
examples, how to use, etc

**Comment by TheRacingLion** [comment]
@eruzang Uhh, anything? You can eval any code. Something like:
`-eval let a = 5; let b = 2; a + b` // 7
You also have access to your discord user from eval, so you can do things like:
`eval self.user.username` // will return your discord username (`self` is the discord client instance)
You can join guilds with eval, leave guilds, add friends, solve math problems, you can eval pretty much anything...
