### ISSUE TITLE
Can't seem to get `noPms: true` to work.

### ISSUE THREAD

**Issue by AriRexouium** [TheRacingLion/Discord-SelfBot#50]
As the name suggests, I've been trying to get `noPms: true` to work for me, but doesn't seem to want to work, if you need my code [here it is](http://gist.github.com/Aceheliflyer/ec8d9c529f38a8c43e6714ab7aeceffa).

*(I assume this is an error on my part since it works with the ban and kick command flawlessly.)*

**Comment by TheRacingLion** [comment]
Your `noPms: true` is inside the embed code. You need to place it in the `registerCommand` code line.

**Comment by TheRacingLion** [comment]
Also, think you can make your code a little bit simpler, by doing something like:
```js
module.exports = (self) => {
  self.registerCommand('perms', function (msg, args) {
    let perms = []
    let userPerms = msg.channel.permissionsOf(msg.author.id).json
    Object.keys(userPerms).forEach((key, index) => {
      perms.push(`${userPerms[key] ? '+' : '-'}${key}`)
    })
    this.embed(msg, { // Send an embed
      title: `${msg.author.username}'s Permissions`,
      description: [
        '```diff',
        perms.join('\n'),
        '```'
      ].join('\n'),
      color: 4627433
    })
  }, {
    noPms: true
  })
}
```

*Note: not tested as I just made it up. Seems like it would work. The `noPms` on this code is in the right place, so check what is different from the one you posted.*

**Comment by AriRexouium** [comment]
Alright, seems to work fine now. Thank you!

**Comment by AriRexouium** [comment]
Except for one thing, the simplified version you have doesn't seem to want to output all the denied permissions.

**Comment by TheRacingLion** [comment]
Ah ye, forgot it doesnt show them on the json cause they are undefined. Oh well, like I said it was made in the moment.
