### ISSUE TITLE
run.bat error

### ISSUE THREAD

**Issue by Arctic5555** [TheRacingLion/Discord-SelfBot#51]
whenever I try to open run.bat I get a repeated error

Checking Config File...
Config is valid. Starting bot...
Loading 12 command files...
Finished
Unclean WS close: 4004: authentication failed.
Disconnected from discord

Can you please tell me whats happening or what i did wrong

**Comment by TheRacingLion** [comment]
Most likely case is that you need to update your token on the config. Every time you change your password on discord, your token updates, so I would update it and try again.
