### ISSUE TITLE
Receiving mobile notifications

### ISSUE THREAD

**Issue by cod3dump** [TheRacingLion/Discord-SelfBot#56]
I love your selfbot but ever since using it, I havnt been receiving mobile notifications from discord. I believe it has to do with Discord thinking that I'm active and not afk. Is there something I can do to enable mobile notifications?

**Comment by AriRexouium** [comment]
I've noticed the same thing, but I don't think it's possible.

**Comment by GabrielSerealia** [comment]
Took me a while to figure this out too, but yeah same problem

**Comment by TheRacingLion** [comment]
Ye, I don't think I can fix this on my end? Like you said, discord probably thinks that you are active so you don't need notifications? I will close for now, but if there is something I can do to fix this, let me know.
