### ISSUE TITLE
Game cycling broken

### ISSUE THREAD

**Issue by ghost** [TheRacingLion/Discord-SelfBot#57]
Call me stupid, but I've enabled game cycling and its the default timing, am I getting something horribly wrong? The function doesn't work at all, and I tested my theory by putting a alternate account on the same discord to see if it cycled, but it didn't. Is anyone else having this same issue?

(If you want my config, I'll give you it but ofc without the token)

**Comment by AriRexouium** [comment]
Did you put games in the game config file?

**Comment by TheRacingLion** [comment]
Don't forget you can't see the games actually rotating. Only other people can see it. Idk if that is the problem, but if it isn't then I'll need the config (without token).

**Comment by TheRacingLion** [comment]
If the comments above are not the reason why it doesn't work, then feel free to re-open
