### ISSUE TITLE
Is there a different way to make Rich Embeds?

### ISSUE THREAD

**Issue by AriRexouium** [TheRacingLion/Discord-SelfBot#58]
I'm currently trying to make a rich embed that uses fields. I know there is a way to do it with the selfbot at the current time, but it doesn't support fields yet? I tried looking at Eris documentation, but don't see anything. Is there a way I can do this or am I missing something here?
(Not sure if this is the right place to ask.)

**Comment by TheRacingLion** [comment]
The selfbot currently has no command where you can create a rich embed with almost anything, the closest it has is the `-me` command. If you want to give a shot at making a command where you can use fields I would sugest using the `this.embed()` function in the selfbot and then taking a look at this link:
[Discord Embed Docs](https://discordapp.com/developers/docs/resources/channel#embed-object)

Would be something like:
```js
this.embed(msg, { // Send an embed
  title: 'Embed title',
  description: 'Embed description',
  fields: [
    {
      'name': 'Some field name',
      'value': 'Some value',
      'inline': false
    },
    {
      'name': 'Some field name',
      'value': 'Some value',
      'inline': false
    },
  ]
  color: 4627433
})
```
And then just use the `args` from the command file to be able to change field content with the command, so something like `'name': args[1]`.

Hope it helps. ~Lion

**Comment by AriRexouium** [comment]
Thank you, I'll have to see if this works.

**Comment by achsolikin** [comment]
Go
