### ISSUE TITLE
selfbot returns "invalid ownerID. Must be a string of your own discord ID."

### ISSUE THREAD

**Issue by Fifkee** [TheRacingLion/Discord-SelfBot#59]
### Thank you for your support.

{
  "token": "***************************************************************************************",
  "ownerID": "what2do, tried my ownerid (not my #9971 stuff)",
  "prefix": "!!",
  "rotatePlayingGame": true,
  "rotatePlayingGameTime" : 150000,
  "rotatePlayingGameInStreamingStatus": false,
  "rotateAvatarImage": true,
  "rotateAvatarImageTime" : 600000,
  "defaultStatus": "idle",
  "PSN": {
    "enabled": false,
    "email": "Your PSN E-mail",
    "password": "Your PSN password",
    "psnID": "Your PSNid"
  },
  "XBOX": {
    "enabled": false,
    "gamertag": "Your XBOX Gamertag",
    "apikey": "Your xboxapi.com apikey"
  },
  "mentionNotificator": {
    "inConsole": true,
    "inNotificationChannel": false,
    "logBlockedUsers": false,
    "ignoredServers": ["SERVER ID"]
  },
  "keywordNotificator": {
    "inConsole": true,
    "inNotificationChannel": false,
    "logBlockedUsers": false,
    "caseInsensitive": true,
    "ignoredServers": ["SERVER ID"]
  },
  "eventNotificator": {
    "inConsole": true,
    "inNotificationChannel": false
  },
  "notificationChannelID": "Notification channel ID if you set 'inNotificationChannel' to true at least once",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": true,
  "deleteCommandMessagesTime": 15000
}

**Comment by AriRexouium** [comment]
That's your Username and Discriminator you're trying to use.
Enable Developer mode by going to `User Settings > Appearance > Developer Mode`.
*Note: Some bots can get you your ID for you.*
After you do that, go to a window that you can right click on your name that brings up a window.
`Right Click on your name > Copy ID`
Your ID is an 18 digit number, this is what you want to use for ownerID.

Here is an example.
```json
"ownerID": "123456789012345678",
```

**Comment by Aceheliflyer** [comment]
Enable Developer mode in the Appearance settings on your Discord client and right click on your username in chat, click on `Copy ID`. This is what you want.

*Note: Some bots can do this for you.*

**Comment by Aceheliflyer** [comment]
Since you're saying your ID doesn't work, I'm not sure what the problem is. Try redownloading the bot?

**Comment by Fifkee** [comment]
No, no, no. I did try my userID. Hopefully it's not confusing, but I typed for userID..:

"ownerID": "what2do, tried my ownerid (not my #9971 stuff)",

**Comment by AriRexouium** [comment]
Are you sure you're using your using your token as the ownerID and or a different account token?
Other than that, I don't know. Could be a setup issue. Try reinstalling the bot?

**Comment by Fifkee** [comment]
Yeah, I'm sure. It works now, though. I guess the bot was broken or something.. I didn't do anything to the .js code, so that's odd. Whatever though, atleast it works, now. Thanks for the help, though! Closing this, I guess.

**Comment by AriRexouium** [comment]
Not a problem.
