### ISSUE TITLE
[Question] If possible, how can I generate a *new token for my account*?

### ISSUE THREAD

**Issue by Campiotti** [TheRacingLion/Discord-SelfBot#63]
**I'd like to generate a new token for my account** just incase I left my token somewhere where someone else could be able to find it (and mis-use it).

Do you know of any way to make discord create a new Token?

Thanks!

**Comment by AriRexouium** [comment]
A while back I heard you couldn't change it even if you changed your password, but i'm pretty if you change your password your token will change too.

**Comment by TheRacingLion** [comment]
Correct. Changing your discord password will reset your token.
