### ISSUE TITLE
Unclean WS close 4004 authentication failed. What does this mean, and how can I fix it?

### ISSUE THREAD

**Issue by Jacob-Pickard** [TheRacingLion/Discord-SelfBot#64]
Everytime I try to run the selfbot i get this error. Is there a fix for it? Im new to coding and discord bots.
![image](https://user-images.githubusercontent.com/33008783/31865949-6528bb6c-b72c-11e7-8838-86443289af77.png)

**Comment by AriRexouium** [comment]
Might be your token. Make sure your token is correct. I could be wrong.

**Comment by TheRacingLion** [comment]
Your token is outdated or you inserted the wrong one. Don't forget the token changes everytime you change your discord password. Check your token, and try again.
