### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by RickRolled7891** [TheRacingLion/Discord-SelfBot#7]
Everytime I try starting the bot I keep getting this
![screenshot_1](https://cloud.githubusercontent.com/assets/20073947/23094213/d05e5e40-f5c2-11e6-86eb-0db64b3ad8c5.png)

**Comment by TheRacingLion** [comment]
What is your node version? Check by doing `node -v`. Make sure you are on the current 7+ version

**Comment by RickRolled7891** [comment]
I was on 6 :o
