### ISSUE TITLE
Getting this issue. how do I fix?

### ISSUE THREAD

**Issue by KittyMOD-Support** [TheRacingLion/Discord-SelfBot#71]
SyntaxError: C:\Users\NAME\Desktop\Discord-SelfBot-master\config\config.json: Unexpected string in JSON at position 441
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:662:27)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\NAME\Desktop\Discord-SelfBot-master\self.js:15:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

**Comment by AriRexouium** [comment]
Send your `config.json` file, be sure to remove your token for obvious reasons.

**Comment by KittyMOD-Support** [comment]
@Aceheliflyer I just found my issue some of the parts don't have commas I must've accidently removed them. Thanks for your help. :)

**Comment by KittyMOD-Support** [comment]
@Aceheliflyer

`{
  "token": "****ODk2Nj*********************************4SX26es*********",
  "ownerID": "329286944565755917",
  "prefix": "!",
  "rotatePlayingGame": false,
  "rotatePlayingGameTime" : 150000,
  "rotatePlayingGameInStreamingStatus": false,
  "rotateAvatarImage": galse,
  "rotateAvatarImageTime" : 600000,
  "defaultStatus": "idle",
  "PSN": {
    "enabled": true,
    "email": "pricetagstudios@gmail.com",
    "password": "Cookie2001",
    "psnID": "Gtaplayer0264"
  },
  "XBOX": {
    "enabled": false,
    "gamertag": "Your XBOX Gamertag",
    "apikey": "Your xboxapi.com apikey"
  },
  "mentionNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
	"ignoredServers": ["SERVER ID"],
  },
  "keywordNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
    "caseInsensitive": true,
	"ignoredServers": ["SERVER ID"],
  },
  "eventNotificator": {
    "inConsole": true,
    "inNotificationChannel": true
  },
  "notificationChannelID": "401895848490827777",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": true,
  "deleteCommandMessagesTime": 15000
}`

**Comment by AriRexouium** [comment]
@KittyMOD-Support Try this:
```json
{
  "token": "****ODk2Nj*********************************4SX26es*********",
  "ownerID": "329286944565755917",
  "prefix": "!",
  "rotatePlayingGame": false,
  "rotatePlayingGameTime": 150000,
  "rotatePlayingGameInStreamingStatus": false,
  "rotateAvatarImage": false,
  "rotateAvatarImageTime": 600000,
  "defaultStatus": "idle",
  "PSN": {
    "enabled": true,
    "email": "pricetagstudios@gmail.com",
    "password": "Cookie2001",
    "psnID": "Gtaplayer0264"
  },
  "XBOX": {
    "enabled": false,
    "gamertag": "Your XBOX Gamertag",
    "apikey": "Your xboxapi.com apikey"
  },
  "mentionNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
    "ignoredServers": [
      "SERVER ID"
    ]
  },
  "keywordNotificator": {
    "inConsole": true,
    "inNotificationChannel": true,
    "logBlockedUsers": false,
    "caseInsensitive": true,
    "ignoredServers": [
      "SERVER ID"
    ]
  },
  "eventNotificator": {
    "inConsole": true,
    "inNotificationChannel": false
  },
  "notificationChannelID": "401895848490827777",
  "defaultEmbedColor": "#117ea6",
  "deleteCommandMessages": true,
  "deleteCommandMessagesTime": 15000
}
```

**Comment by KittyMOD-Support** [comment]
@Aceheliflyer thanks for the help but that didn't fix it I screwed up on the text for games.json but I reinptued the script and now it works. Thanks so much for your help! <3
