### ISSUE TITLE
Invalid Owner ID

### ISSUE THREAD

**Issue by KittyMOD-Support** [TheRacingLion/Discord-SelfBot#72]
I'm getting an invalid owner ID even though it is right. How can this issue be fixed? 
![image](https://user-images.githubusercontent.com/34408234/34920274-cae5de9e-f935-11e7-89c3-6b9711d270fb.png)

**Comment by AriRexouium** [comment]
Make sure you're using your ID and not your username/discriminator.

**Comment by KittyMOD-Support** [comment]
@Aceheliflyer I did it didn't work still.

**Comment by TheRacingLion** [comment]
@KittyMOD-Support Make sure your token is correct and updated.
