### ISSUE TITLE
Rich Game Cycling?

### ISSUE THREAD

**Issue by MayhemBill** [TheRacingLion/Discord-SelfBot#74]
I know you have Game cycles and stream cycles, but can I do a rich presence style cycle? or have it mix with the games?

**Comment by sn8to** [comment]
Rich presence requires a lot of setup beforehand on your own account + tell Discord to add your account + link to the RPC some-fucking-how + you only have a 50 asset limit anyways.

**Comment by TheRacingLion** [comment]
Sorry for the late reply. But like the reply above said. I will not adding support for this.
