### ISSUE TITLE
Commands not always listening??

### ISSUE THREAD

**Issue by cybergodjsp** [TheRacingLion/Discord-SelfBot#75]
As seen in picture

![Image of Yaktocat](https://i.gyazo.com/1c8e0472a201af93125edea13ba9a75c.png)

The image keeps being changed no problem but its not always seeing my commands in private messages, I -prune # my dms alot and its really annoying if im on my phone and -prune # doesnt work... I then have to teamviewer my computer and exit out and open it again.

**Comment by AriRexouium** [comment]
Make sure you didn't highlight any text in the console/terminal. Also make sure your computer is on, but since you mentioned TeamViewer I doubt that could be the case.

**Comment by cybergodjsp** [comment]
nope, any other ideas?

I just open it and minimize it.
