### ISSUE TITLE
can you do a updated one for microsoft edge?

### ISSUE THREAD

**Issue by ZxkPencils** [TheRacingLion/Discord-SelfBot#78]
I have been trying to find my token but inspect element on Microsoft edge dosnt even have the application tab you are trying to get me to find it in so I was wondering what it would be in other wise

**Comment by TheRacingLion** [comment]
1. Open Edge
2. Login to discord
3. Press `Ctrl + Shift + i`
4. In the top you should have `Elements` `Console` `Debugger`.
5. Press `Debugger` or just `Ctrl + 3`
6. On the side tab press on `Local Storage`
7. Press on the discord link inside it
8. Search for the `token` and copy the text between the `"`
