### ISSUE TITLE
Selfbot registers commands from others

### ISSUE THREAD

**Issue by rjt-rockx** [TheRacingLion/Discord-SelfBot#8]
Commands like `nick` sent by non-selfbot users are evaluated with an unhandled Promise exception, basically letting others change our nickname at will if they know the prefix. 
I'm guessing the problem might be in the defaultCommandOptions.

**Comment by TheRacingLion** [comment]
I will be getting rid of the library command client to my own handler, so I have more control over the bot itself and to be easier to add in features. But nevertheless, I will look into it and see what could be causing it.

**Comment by rjt-rockx** [comment]
Looks like the problem is with Eris not recognising the UserId requirement in defaultCommandOptions 🤔

**Comment by TheRacingLion** [comment]
[**This commit**](https://github.com/TheRacingLion/Discord-SelfBot/commit/88a4a4bc6ac46c0816ad1855215143d4fd87e626) should fix that issue. Lmk if there are any bugs.
