### ISSUE TITLE
Embedding Message Question

### ISSUE THREAD

**Issue by DrEnder** [TheRacingLion/Discord-SelfBot#9]
How can I do a rich text form for embed messages? I want a footer, rich text format, icon of server and multiple lines (fields). Please get to me asap. Thanks!

**Comment by DrEnder** [comment]
Sorry, sort of new to this :)

**Comment by TheRacingLion** [comment]
I will asume you are asking a code related question, so to make embeds in the commands, you can use `this.embed(msg, embedObject)` to have the bot send an embed, an example of a embed object would be something like:
```js
{
  color: 1,
  description: 'This is an embed description',
  fields: [
    { title: 'Some title', value: 'Some info', inline: true },
    { title: 'Some other title', value: 'Some more info', inline: false }
  ],
  footer: {
    text: 'This would be the footer text'
  }
}
```
You can get info about all fields that you can use in here:
https://discordapp.com/developers/docs/resources/channel#embed-object
